---
- name: DELETE USERS
  hosts: localhost
  gather_facts: no
  become: true
  tasks:
  - name: create users
    user:
      name: "{{item}}"
      groups: test
      state: absent
    with_items:
        - carrot
