---
- name: SSHD UPDATE AND RESTART
  hosts: localhost
  gather_facts: no
  become: true
  vars:
   sshd_path: "/etc/ssh/sshd_config"
   sshd_backup_path: "/etc/ssh/sshd_config.backup"
   regex_pattern: "s/^#?Port 22$/Port 6522/"
  tasks:
  - name: Backup Original sshd_config
    copy:
     src: "{{sshd_path}}"
     dest: "{{sshd_backup_path}}"
  - name: Update sshd_config
    lineinfile:
     path: "{{sshd_path}}"
     regex: "{{regex_pattern}}"
     state: present
    notify:
     - restart sshd
     - restart ssh
  handlers:
  - name: restart sshd
    service:
     name: sshd
     state: restarted
    become: true
  - name: restart ssh
    service:
     name: ssh
     state: restarted
    become: true
    
