---
- name: LOGROTATE COPY
  hosts: localhost
  gather_facts: true
  become: true
  vars:
   logrotate_config_file: "logrotate.conf"
   logrotate_path: "/etc/"
   logrotate_config_path: "/etc/logrotate.d/"
  tasks:
  - name: Copy Logrotate config
    copy:
     src: "{{logrotate_path}}{{logrotate_config_file}}"
     dest: "{{logrotate_config_path}}{{logrotate_config_file}}"
