---
- name: INSTALL PACKAGES
  hosts: localhost
  gather_facts: true
  become: true
  tasks:
  - name: install packages
    apt:
     name: "{{item}}"
     state: present
    with_items:
     - wget
     - unzip
     - curl
     - git
     - jq
     - apache2
     - mysql-client
     - php
