---
- name: create temp directory
  hosts: all
  gather_facts: no
  become: true
  vars:
   tmp_dir_name: /tmp/fefiles
  tasks:
  - name: create temp directory
    file:
     path: "{{temp_dir_name}}"
     state: directory