---
- name: curl html from S3
  hosts: localhost
  vars:
   ACCESS_KEY_ID: "AKIA4O6YRV2IUN74EC2K"
   SECRET_ACCESS_KEY: "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"
   region: "us-east-2"
   bucket_name: "skillup-s3-a.armas-002"
   object_own: "BucketOwnerEnforced"
   mode: "get"
   dest_dir: "/var/www/html/"
   object: "index.html"
  tasks:
  - name: curl html from S3
    amazon.aws.s3_object:
     access_key: "{{ACCESS_KEY_ID}}"
     secret_key: "{{SECRET_ACCESS_KEY}}"
     region: "{{region}}"
     bucket: "{{bucket_name}}"
     object_ownership: "{{object_own}}"
     mode: "{{mode}}"
     object: "{{object}}"
     dest: "{{dest_dir}}{{object}}"
