---
- name: curl html from S3
  hosts: localhost
  vars:
   bucket_name: "skillup-s3-a.armas-002"
   mode: "get"
   dest_dir: "/var/www/html/"
   object: "index.html"
  tasks:
  - name: curl html from S3
    amazon.aws.s3_object:
     bucket: "{{bucket_name}}"
     mode: "{{mode}}"
     object: "{{object}}"
     dest: "{{dest_dir}}{{object}}"
