---
- name: CREATE USERS
  hosts: localhost
  gather_facts: no
  become: true
  tasks:
  - name: create users
    user:
      name: "{{item}}"
      groups: users
      state: present
    with_items:
        - apple
        - banana
        - carrot
